# Generated by Django 6.0.2 on 2026-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_task_category_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal')], default='WORK', max_length=10),
        ),
    ]
